from pydantic import BaseModel
from typing import Optional

class StoreBase(BaseModel):
    name: str
    location: str
    manager: str
    eslCount: int
    status: str
    lastSync: Optional[str] = None

class StoreCreate(BaseModel):
    name: str
    location: str
    manager: str
    eslCount: int = 0
    status: str = "active"
    lastSync: Optional[str] = None

class StoreUpdate(BaseModel):
    name: Optional[str] = None
    location: Optional[str] = None
    manager: Optional[str] = None
    eslCount: Optional[int] = None
    status: Optional[str] = None
    lastSync: Optional[str] = None

class StoreInDB(StoreBase):
    id: str
    managerId: str  # Auto-generated by backend

class Store(StoreInDB):
    pass 